'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),A=require('../../games/atlas'),D=require('../../games/data/atlas-data.json');
const make=options=>A.create(D,{seed:'proof',now:1000,sessionId:'test-session',...options});
function complete(state){let count=0;while(state.status!=='finished'){if(++count>110)throw Error('Run did not terminate');const c=A.currentCountry(D,state);state=A.answer(D,state,{type:'guess',value:['typing','reasoning'].includes(state.mode)?c.name:c.id,roundKey:A.roundKey(state)});state=A.next(state,A.roundKey(state));}return state;}
test('complete ten-target expedition and full Classic, Hard and Typing runs terminate with accuracy-only score',()=>{for(const mode of ['expedition','classic','hard','typing','reasoning']){const s=complete(make({mode})),r=A.summary(s);assert.equal(r.total,['expedition','reasoning'].includes(mode)?10:50);assert.equal(r.correct,r.total);assert.equal(r.score,r.total*100);assert.equal(r.maxScore,r.score);assert.equal(r.mode,mode);assert.equal(r.assistance,0);}});
test('fixed seed and content edition keep targets identical, while supplied daily targets remain exact',()=>{assert.deepEqual(make({mode:'classic'}).targets,make({mode:'classic'}).targets);assert.notDeepEqual(make({mode:'classic',seed:'other'}).targets,make({mode:'classic'}).targets);assert.deepEqual(make({targets:['USA','IDN','MDG']}).targets,['USA','IDN','MDG']);assert.throws(()=>make({targets:['ZZZ']}),/ISO3/);});
test('score rewards accuracy first, caps hints, and never awards reveal or speed points',()=>{assert.equal(A.score(1,0),100);assert.equal(A.score(2,0),60);assert.equal(A.score(3,0),30);assert.equal(A.score(12,0),30);assert.equal(A.score(1,1),30);assert.equal(A.score(1,2),30);assert.equal(A.score(0,3),0);let s=make({targets:['USA','IDN']});s=A.answer(D,s,{type:'guess',value:'CAN'});s=A.answer(D,s,{type:'guess',value:'USA'});assert.equal(s.results[0].score,60);s=A.next(s);s=A.answer(D,s,{type:'hint'});s=A.answer(D,s,{type:'reveal'});assert.equal(s.results[1].score,0);assert.equal(s.results[1].correct,false);assert.equal(A.summary(s).score,60);});
test('explicit feedback, stale round keys, repeated taps and pause cannot duplicate points or skip a target',()=>{let s=make({targets:['USA','IDN']});const key=A.roundKey(s);const wrong=A.answer(D,s,{type:'guess',value:'CAN',roundKey:key});assert.equal(A.answer(D,wrong,{type:'guess',value:'CAN',roundKey:key}),wrong);s=A.answer(D,s,{type:'guess',value:'USA',roundKey:key});assert.equal(A.answer(D,s,{type:'guess',value:'USA',roundKey:key}),s);const next=A.next(s,key);assert.equal(A.next(next,key),next);assert.equal(A.answer(D,next,{type:'guess',value:'IDN',roundKey:key}),next);const paused={...next,paused:true};assert.equal(A.answer(D,paused,{type:'reveal'}),paused);const pausedFeedback={...s,paused:true};assert.equal(A.next(pausedFeedback),pausedFeedback);});
test('missed expedition targets return as unscored review and do not inflate initial accuracy or mastery',()=>{let s=make({targets:['USA','IDN','MDG','CIV']});s=A.answer(D,s,{type:'reveal'});assert.equal(s.queue.filter(q=>q.id==='USA').length,2);s=A.next(s);s=complete(s);const r=A.summary(s);assert.equal(r.total,4);assert.equal(r.results.length,4);assert.equal(r.reviewResults.length,1);assert.equal(r.score,300);assert.equal(r.correct,3);assert.equal(r.reviewResults[0].correct,true);});
test('save/restore keeps exact target, attempts, assistance, camera, typed text and feedback phase',()=>{let s=make({mode:'typing',targets:['USA','IDN']});s=A.answer(D,s,{type:'guess',value:'Canada'});s=A.answer(D,s,{type:'hint'});s=A.answer(D,s,{type:'type',value:'United Stat'});s.view=A.zoom(s.view,3);const restored=A.restore(D,JSON.parse(JSON.stringify(s)));assert.equal(restored.ok,true);assert.deepEqual(restored.state,s);assert.equal(A.restore(D,{...s,contentVersion:'future'}).ok,false);assert.equal(A.restore(D,{...s,index:-1}).ok,false);assert.equal(A.restore(D,null).ok,false);});
test('durable recall requires independent attempts separated by sessions and at least one day',()=>{const result=A.summary(complete(make({targets:['USA']})));let m=A.updateMastery({},result,1000);assert.equal(m.USA.level,'found independently');m=A.updateMastery(m,result,90000000);assert.equal(m.USA.history.length,1);m=A.updateMastery(m,{...result,sessionId:'immediate-repeat'},2000);assert.equal(m.USA.level,'found independently');m=A.updateMastery(m,{...result,sessionId:'tomorrow'},86402000);assert.equal(m.USA.level,'recalled independently');let reveal=make({targets:['USA']});reveal=A.next(A.answer(D,reveal,{type:'reveal'}));reveal=complete(reveal);assert.equal(A.updateMastery({},A.summary(reveal),1000).USA.level,'found with help');});
test('pan and zoom clamp within the world and never choose a target location',()=>{const original={x:0,y:0,width:1080,height:540};assert.deepEqual(A.zoom(original,.5),original);const zoom=A.zoom(original,100);assert.equal(zoom.width,67.5);assert.equal(zoom.x+zoom.width/2,540);assert.equal(zoom.y+zoom.height/2,270);assert.deepEqual(A.clampView({x:-500,y:999,width:270}),{x:0,y:405,width:270,height:135});});
test('exposure becomes a completed record in the same session and different modes cannot manufacture durable recall',()=>{let s=make({mode:'typing',targets:['USA','IDN']});let m=A.updateMastery({},A.summary(s),1000);assert.equal(m.USA.level,'seen');assert.equal(m.IDN,undefined);s=A.answer(D,s,{type:'guess',value:'USA'});m=A.updateMastery(m,A.summary(s),2000);assert.equal(m.USA.history.length,1);assert.equal(m.USA.level,'found independently');const later=A.summary(complete(make({mode:'classic',sessionId:'different-mode',targets:['USA']})));m=A.updateMastery(m,later,90000000);assert.equal(m.USA.level,'found independently');});
test('restore rejects impossible feedback and duplicate review records without altering the original object',()=>{let s=make({targets:['USA','IDN']});s=A.answer(D,s,{type:'reveal'});assert.equal(A.restore(D,s).ok,true);const corrupt=JSON.parse(JSON.stringify(s));corrupt.current.correct=true;const bytes=JSON.stringify(corrupt);assert.equal(A.restore(D,corrupt).ok,false);assert.equal(JSON.stringify(corrupt),bytes);const duplicate=JSON.parse(JSON.stringify(s));duplicate.queue.push({id:'USA',review:true});assert.equal(A.restore(D,duplicate).ok,false);const badResult=complete(make({targets:['USA']}));badResult.results[0].attempts=0;assert.equal(A.restore(D,badResult).ok,false);});
