(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.NoteworthyEvidenceVisuals=api;})(typeof window==='object'?window:this,function(){'use strict';
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function chartData(chart,expanded=false){if(!chart||!Array.isArray(chart.labels)||!Array.isArray(chart.values)||chart.labels.length!==chart.values.length||chart.values.length<2||chart.values.length>8||!chart.values.every(Number.isFinite))return null;const min=expanded?0:Number(chart.croppedMin??0),max=Number(chart.max??Math.max(...chart.values));if(!Number.isFinite(min)||!Number.isFinite(max)||min>=max||chart.values.some(v=>v<min||v>max))return null;return{min,max,rows:chart.values.map((value,i)=>({label:chart.labels[i],value,fraction:(value-min)/(max-min)})),unit:chart.unit||'units'};}
 function render(item,options={}){let out='';const data=chartData(item.chart,options.expanded);if(data){const width=500,height=230,left=65,right=20,top=23,bottom=45,plotH=height-top-bottom,plotW=width-left-right,slot=plotW/data.rows.length,bar=Math.min(70,slot*.6);out+=`<figure class="evidence-graphic"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Simulated chart. Axis starts at ${data.min}; values ${esc(data.rows.map(r=>r.label+' '+r.value).join(', '))}. Equivalent table follows.">${[0,.25,.5,.75,1].map(t=>`<path d="M${left} ${top+plotH*(1-t)}H${width-right}" stroke="#bac9c6" stroke-width="1"/><text x="${left-10}" y="${top+plotH*(1-t)+4}" text-anchor="end">${Number((data.min+(data.max-data.min)*t).toFixed(2))}</text>`).join('')}${data.rows.map((r,i)=>`<rect x="${left+slot*i+(slot-bar)/2}" y="${top+plotH*(1-r.fraction)}" width="${bar}" height="${plotH*r.fraction}" fill="${i%2?'#276d77':'#6d9898'}"/><text x="${left+slot*(i+.5)}" y="${top+plotH*(1-r.fraction)-7}" text-anchor="middle" font-weight="700">${r.value}</text><text x="${left+slot*(i+.5)}" y="${height-19}" text-anchor="middle">${esc(r.label)}</text>`).join('')}</svg><figcaption>Constructed chart · ${esc(data.unit)} · Axis starts at ${data.min}</figcaption></figure><button type="button" class="g-button g-button-small" data-chart-toggle="${esc(item.id)}">${options.expanded?'Restore the published crop':'Expand to a zero baseline'}</button><table class="evidence-data"><caption>The same simulated values in both views</caption><thead><tr><th>Record</th><th>${esc(data.unit)}</th></tr></thead><tbody>${data.rows.map(r=>`<tr><th>${esc(r.label)}</th><td>${r.value}</td></tr>`).join('')}</tbody></table>`;}
  const chain=item.sourceChain;if(chain&&Array.isArray(chain.nodes)&&Array.isArray(chain.edges)&&chain.nodes.length<=12&&chain.nodes.length){const nodes=chain.nodes,positions=new Map(nodes.map((n,i)=>[n.id,{x:230,y:35+i*65}])),height=nodes.length*65+10;out+=`<figure class="evidence-graphic"><svg viewBox="0 0 460 ${height}" role="img" aria-label="Simulated source trail. Arrows mean cites. An equivalent relationship list follows."><defs><marker id="evidence-arrow-${esc(item.id)}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#306d74"/></marker></defs>${chain.edges.filter(e=>positions.has(e.from)&&positions.has(e.to)).map(e=>{const a=positions.get(e.from),b=positions.get(e.to),direction=b.y>a.y?1:-1;return `<path d="M${a.x} ${a.y+direction*19}L${b.x} ${b.y-direction*22}" stroke="#306d74" stroke-width="2" marker-end="url(#evidence-arrow-${esc(item.id)})"/>`;}).join('')}${nodes.map(n=>{const p=positions.get(n.id);return `<rect x="70" y="${p.y-18}" width="320" height="36" rx="3" fill="#d7e5df" stroke="#718f8e"/><text x="230" y="${p.y+5}" text-anchor="middle">${esc(n.label)}</text>`;}).join('')}</svg><figcaption>Constructed source trail · Arrows mean ${esc(chain.arrowMeaning||'cites')}</figcaption></figure><details><summary>Read the source relationships</summary><ul>${chain.edges.map(e=>`<li>${esc(nodes.find(n=>n.id===e.from)?.label||e.from)} ${esc(chain.arrowMeaning||'cites')} ${esc(nodes.find(n=>n.id===e.to)?.label||e.to)}</li>`).join('')}</ul></details>`;}
  const table=item.table;if(table&&Array.isArray(table.columns)&&Array.isArray(table.rows))out+=`<div class="evidence-table-wrap"><table class="evidence-data"><caption>Original simulated case data</caption><thead><tr>${table.columns.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${table.rows.map(row=>`<tr>${row.map((v,i)=>`<${i?'td':'th'}>${esc(v)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  if(Array.isArray(item.timestamps))out+=`<ol class="evidence-timeline" aria-label="Simulated record timestamps">${item.timestamps.map(t=>`<li><strong>${esc(t.label)}</strong><time datetime="${esc(t.value)}">${esc(String(t.value).replace('T',' ').replace('Z',' UTC'))}</time></li>`).join('')}</ol>`;
  return out;
 }
 return{chartData,render};
});
