#!/usr/bin/env node
'use strict';

/**
 * Install Chrome Native Messaging host for Noteworthy clip MP4 conversion.
 *
 * Usage:
 *   npm run clip:install-native-host
 *   npm run clip:install-native-host -- YOUR_EXTENSION_ID
 *   npm run clip:install-native-host -- ID1 ID2   (register multiple IDs)
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execSync } = require('child_process');

const HOST_NAME = 'com.noteworthy.clip';
const HOST_DIR = __dirname;
const HOST_SCRIPT = path.join(HOST_DIR, 'noteworthy-clip-host.js');
const HOST_WRAPPER = path.join(HOST_DIR, 'noteworthy-clip-host.sh');

function resolveNodePath() {
  if (process.execPath && fs.existsSync(process.execPath)) {
    return process.execPath;
  }
  try {
    return execSync('command -v node', { encoding: 'utf8' }).trim();
  } catch {
    const candidates = [
      '/usr/local/bin/node',
      '/opt/homebrew/bin/node',
      '/usr/bin/node',
    ];
    const found = candidates.find((p) => fs.existsSync(p));
    if (found) return found;
    throw new Error('Could not find node — run install with node on PATH');
  }
}

function writeHostWrapper(nodePath) {
  const content = `#!/bin/bash
# Generated by npm run clip:install-native-host — do not edit
exec ${JSON.stringify(nodePath)} ${JSON.stringify(HOST_SCRIPT)}
`;
  fs.writeFileSync(HOST_WRAPPER, content, { mode: 0o755 });
}

function browserNativeHostDirs() {
  const home = os.homedir();
  const dirs = [
    path.join(home, 'Library/Application Support/Google/Chrome/NativeMessagingHosts'),
    path.join(home, 'Library/Application Support/Chromium/NativeMessagingHosts'),
    path.join(home, 'Library/Application Support/Microsoft Edge/NativeMessagingHosts'),
    path.join(home, 'Library/Application Support/BraveSoftware/Brave-Browser/NativeMessagingHosts'),
    path.join(home, 'Library/Application Support/Arc/User Data/NativeMessagingHosts'),
  ];

  if (process.platform === 'linux') {
    return [
      path.join(home, '.config/google-chrome/NativeMessagingHosts'),
      path.join(home, '.config/chromium/NativeMessagingHosts'),
      path.join(home, '.config/microsoft-edge/NativeMessagingHosts'),
      path.join(home, '.config/BraveSoftware/Brave-Browser/NativeMessagingHosts'),
    ];
  }

  if (process.platform === 'win32') {
    throw new Error('Windows: register via registry — see native-host/README.md');
  }

  if (process.platform !== 'darwin') {
    throw new Error(`Unsupported platform: ${process.platform}`);
  }

  return dirs;
}

function clearQuarantine(filePath) {
  try {
    execSync(`xattr -d com.apple.quarantine ${JSON.stringify(filePath)}`, { stdio: 'ignore' });
  } catch {
    /* ignore */
  }
}

function readExistingOrigins(dest) {
  if (!fs.existsSync(dest)) return [];
  try {
    const existing = JSON.parse(fs.readFileSync(dest, 'utf8'));
    return Array.isArray(existing.allowed_origins) ? existing.allowed_origins : [];
  } catch {
    return [];
  }
}

function buildManifest(extensionIds, existingOrigins = []) {
  const origins = [...new Set([
    ...existingOrigins,
    ...extensionIds.map((id) => `chrome-extension://${id}/`),
  ])];

  return {
    name: HOST_NAME,
    description: 'Noteworthy News clip WebM to MP4 converter',
    path: HOST_WRAPPER,
    type: 'stdio',
    allowed_origins: origins,
  };
}

function main() {
  const ids = process.argv.slice(2).filter(Boolean);

  if (ids.length === 0 && process.env.NOTEWORTHY_EXTENSION_ID) {
    ids.push(process.env.NOTEWORTHY_EXTENSION_ID);
  }

  const extensionIds = ids.filter(Boolean);

  if (extensionIds.length === 0) {
    console.error(`Usage: npm run clip:install-native-host -- EXTENSION_ID [EXTENSION_ID2 ...]

Get EXTENSION_ID from the Noteworthy extension popup (or chrome://extensions).

Example:
  npm run clip:install-native-host -- abcdefghijklmnopqrstuvwxyz123456`);
    process.exit(1);
  }

  if (!fs.existsSync(HOST_SCRIPT)) {
    console.error('Host script missing:', HOST_SCRIPT);
    process.exit(1);
  }

  const nodePath = resolveNodePath();
  writeHostWrapper(nodePath);
  fs.chmodSync(HOST_SCRIPT, 0o755);
  fs.chmodSync(HOST_WRAPPER, 0o755);
  clearQuarantine(HOST_SCRIPT);
  clearQuarantine(HOST_WRAPPER);

  const installed = [];

  for (const dir of browserNativeHostDirs()) {
    try {
      fs.mkdirSync(dir, { recursive: true });
    } catch {
      continue;
    }

    const dest = path.join(dir, `${HOST_NAME}.json`);
    const manifest = buildManifest(extensionIds, readExistingOrigins(dest));
    fs.writeFileSync(dest, JSON.stringify(manifest, null, 2), 'utf8');
    installed.push(dest);
  }

  if (installed.length === 0) {
    console.error('Could not install native messaging host — no browser directories found.');
    process.exit(1);
  }

  console.log(`Installed native messaging host for extension ID(s):
  ${extensionIds.join(', ')}

Node:         ${nodePath}
Host wrapper: ${HOST_WRAPPER}
Host script:  ${HOST_SCRIPT}

Manifest(s):
${installed.map((p) => `  ${p}`).join('\n')}

Next steps:
  1. Quit and reopen Chrome (Cmd+Q — not just close the window)
  2. Reload the Noteworthy extension at chrome://extensions
  3. Open the extension popup — it should say "Automatic MP4 ready"`);
}

main();
