#!/bin/bash
# Generated by npm run clip:install-native-host — do not edit
exec "/usr/local/bin/node" "/Users/richarda/breaking-news-game/scripts/clip-pipeline/browser/native-host/noteworthy-clip-host.js"
