'use strict';

const M = require('./model');
const route = '/inside-the-story/java-sea-2026/';
const title = 'Deep beneath the Java Sea';
const description = 'Explore an earthquake through its recorded location, regional context, estimated shaking and preserved USGS revisions.';
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const json = value => JSON.stringify(value).replace(/</g, '\\u003c');
const number = value => typeof value === 'number' && Number.isFinite(value) ? String(Math.round(value * 10) / 10) : 'Not reported';
const time = value => M.timestamp(value) !== null ? `<time datetime="${new Date(M.timestamp(value)).toISOString()}">${esc(M.formatTime(value))}</time>` : 'Not supplied';
const dateOnly = value => M.timestamp(value) !== null ? new Date(M.timestamp(value)).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}) : 'Not supplied';
const link = (url,label,extra='') => M.httpUrl(url) ? `<a class="inline-source" href="${esc(M.httpUrl(url))}" ${extra}>${esc(label)} <span aria-hidden="true">↗</span></a>` : '';
function dataset() {
  const result = M.prepareData(require('./data/java-sea-2026.json'));
  if (!result.ok || result.warnings.length) throw new Error('Inside the Story data failed validation: '+[...result.errors,...result.warnings].join(' '));
  for (const id of ['origin-earlier','origin-current','shakemap-1','shakemap-4']) {
    const version = result.data.evidence.find(item => item.id === id);
    const source = version && M.sourceById(result.data,version.sourceId);
    if (!version || !source || !M.timestamp(source.issuedAt)) throw new Error('Inside the Story requires its dated source history: '+id);
  }
  if (!result.data.shaking || !result.data.geography || result.data.events.length !== 4) throw new Error('Inside the Story requires its complete curated geography and catalogue.');
  return result.data;
}
function project(data,coordinate,width=800,height=530) { return M.project(coordinate,data.bounds,[width,height]); }
function geometryPath(data,geometry,width=800,height=530) {
  if (!geometry) return '';
  const line = (coordinates,close=false) => coordinates.map((coordinate,index)=>{const point=project(data,coordinate,width,height);return `${index?'L':'M'}${point.x.toFixed(2)},${point.y.toFixed(2)}`;}).join(' ')+(close?' Z':'');
  const c=geometry.coordinates;
  if (geometry.type==='LineString') return line(c);
  if (geometry.type==='MultiLineString') return c.map(points=>line(points)).join(' ');
  if (geometry.type==='Polygon') return c.map(points=>line(points,true)).join(' ');
  if (geometry.type==='MultiPolygon') return c.flatMap(polygon=>polygon.map(points=>line(points,true))).join(' ');
  return '';
}
function map(data,{compact=false}={}) {
  const width=800,height=530,main=project(data,[data.event.longitude,data.event.latitude],width,height);
  const clip=compact?'inside-teaser-clip':'inside-map-clip';
  const [west,south,east,north]=data.bounds;
  const frame = bounds => {const a=project(data,[bounds[0],bounds[3]]),b=project(data,[bounds[2],bounds[1]]);return `${a.x.toFixed(2)} ${a.y.toFixed(2)} ${(b.x-a.x).toFixed(2)} ${(b.y-a.y).toFixed(2)}`;};
  const overviewFrame=frame([104.1,-8.0,110.1,-3.2]);
  const evidenceFrame=frame([105.3,-6.5,108.5,-3.9]);
  const grid=[];
  for(let longitude=Math.ceil(west);longitude<=east;longitude+=2){const a=project(data,[longitude,south]),b=project(data,[longitude,north]);grid.push(`<path class="map-grid" d="M${a.x},${a.y}L${b.x},${b.y}"/><text class="map-tick" x="${a.x+4}" y="${Math.min(height-8,a.y-5)}">${longitude}°E</text>`);}
  for(let latitude=Math.ceil(south);latitude<=north;latitude+=2){const a=project(data,[west,latitude]),b=project(data,[east,latitude]);grid.push(`<path class="map-grid" d="M${a.x},${a.y}L${b.x},${b.y}"/>${latitude===south?'':`<text class="map-tick" x="${Math.max(8,a.x+3)}" y="${a.y-5}">${Math.abs(latitude)}°S</text>`}`);}
  const geo=data.geography?.geojson?.features || [];
  const geoPaths=geo.map(feature=>`<path class="map-land" d="${geometryPath(data,feature.geometry)}" fill-rule="evenodd"/>`).join('');
  const labels=[{text:'SUMATRA',coordinate:[104.7,-4.3],kind:'map-label'},{text:'JAVA',coordinate:[109.0,-7.3],kind:'map-label'},{text:'Java Sea',coordinate:[107.5,-4.15],kind:'map-ocean'},{text:'Indian Ocean',coordinate:[105.9,-8.8],kind:'map-ocean'}].filter(label=>label.coordinate[0]>=west&&label.coordinate[0]<=east&&label.coordinate[1]>=south&&label.coordinate[1]<=north).map(label=>{const p=project(data,label.coordinate);return `<text class="${label.kind}" text-anchor="middle" x="${p.x}" y="${p.y}">${label.text}</text>`;}).join('');
  const shaking=data.shaking?.geojson?.features || [];
  const shakePaths=compact?'':shaking.map(feature=>{const color=/^#[0-9a-f]{6}$/i.test(feature.properties?.color||'')?feature.properties.color:'#91bcdf';return `<path d="${geometryPath(data,feature.geometry)}" fill="${color}" fill-opacity=".8" stroke="none"><title>USGS estimated intensity: ${esc(number(feature.properties?.value))} MMI</title></path>`;}).join('');
  const points=compact?'':data.events.map(event=>{const p=project(data,[event.longitude,event.latitude]);const radius=Math.max(4,Math.min(12,(event.magnitude||3)*1.4));const text=`M${number(event.magnitude)} / ${M.formatTime(event.time)} / ${event.place}`;return `<a href="${route}?insideEvent=${encodeURIComponent(event.id)}" data-inside-event="${esc(event.id)}" data-inside-event-point="${esc(event.id)}" tabindex="-1" aria-label="${esc(text)}"><circle class="map-marker-hit" cx="${p.x}" cy="${p.y}" r="18"/><circle class="map-event" cx="${p.x}" cy="${p.y}" r="${radius}"/><title>${esc(text)}</title></a>`;}).join('');
  return `<svg class="inside-map" ${compact?'aria-hidden="true"':`data-inside-map data-inside-projection-size="800 530" data-inside-view-overview="${overviewFrame}" data-inside-view-sequence="0 0 800 530" data-inside-view-shaking="${evidenceFrame}" data-inside-view-evidence="${evidenceFrame}" role="img" aria-labelledby="inside-map-title inside-map-description"`} viewBox="${compact?'0 0 800 530':overviewFrame}">
    ${compact?'':'<title id="inside-map-title">Java Sea earthquake and regional context</title><desc id="inside-map-description">Geographic map of southern Sumatra and Java. A marker locates the recorded earthquake epicentre. Use the controls and equivalent event list to explore the catalogue, agency shaking estimates and preserved origin versions.</desc>'}
    <defs><clipPath id="${clip}"><rect width="${width}" height="${height}"/></clipPath></defs>
    <g clip-path="url(#${clip})"><rect width="${width}" height="${height}" fill="#e7edf0"/>${grid.join('')}${geoPaths}
      <g data-inside-map-layer="shaking" ${compact?'':'hidden'}>${shakePaths}</g>
      ${labels}<g data-inside-map-layer="sequence" ${compact?'':'hidden'}>${points}</g>
      <g data-inside-map-layer="epicentre"><circle class="map-main-ring" cx="${main.x}" cy="${main.y}" r="24"/><circle class="map-main-dot" cx="${main.x}" cy="${main.y}" r="7" fill="#145ac7" stroke="#fff" stroke-width="2"/><path class="map-main-cross" d="M${main.x},${main.y-13}v26M${main.x-13},${main.y}h26" stroke="#145ac7" stroke-width="1"/><text class="map-main-label" x="${main.x+32}" y="${main.y-4}">M${number(data.event.magnitude)}</text><text class="map-city" x="${main.x+32}" y="${main.y+15}">Recorded epicentre</text></g>
      ${compact?'':'<g data-inside-evidence-marker hidden><circle r="14" fill="none" stroke="#a45421" stroke-width="2"/><path d="M-5,-5L5,5M5,-5L-5,5" stroke="#a45421" stroke-width="2"/></g>'}
    </g><path d="M755 50v-24m-5 6 5-6 5 6" stroke="#4d687b" fill="none"/><text x="755" y="19" text-anchor="middle" class="map-tick">N</text>
  </svg>`;
}

function feature() {
  const data=dataset();
  return `<section class="inside-feature" aria-labelledby="inside-feature-title"><div class="inside-feature-copy"><div class="eyebrow">Inside the Story / Visual explanation</div><h2 id="inside-feature-title"><a href="${route}">Deep beneath<br>the Java Sea.</a></h2><p>One earthquake. A changing picture. Explore the preserved USGS estimates and the evidence behind them.</p><a class="button button-blue" href="${route}">Explore the visual story <span aria-hidden="true">→</span></a><span class="inside-feature-date">September 11, 2026 UTC earthquake / Source archive</span></div><a class="inside-feature-map" href="${route}" tabindex="-1" aria-hidden="true">${map(data,{compact:true})}<span class="inside-feature-map-label">M${number(data.event.magnitude)} / ${number(data.event.depthKm)} km deep <span>USGS source estimate</span></span></a></section>`;
}

function articleContext(id) {
  if(id!=='usgs-us7000tgrk')return '';
  return `<aside class="story-context"><div class="eyebrow">A later USGS estimate is available</div><p>The preserved source history includes an earlier M6.6 estimate and a later M6.5 solution. Explore the revisions, their dates and the agency’s estimated shaking.</p><a class="text-link" href="${route}">Inside the Story: the Java Sea earthquake →</a><span class="small">The original update below retains its publication time and source values.</span></aside>`;
}

function evidenceCard(data,evidence) {
  if(!evidence)return '<p>No earlier source version has been preserved for this feature.</p>';
  const source=M.sourceById(data,evidence.sourceId);
  return `<h3>${esc(evidence.label)}</h3><p>${esc(evidence.text)}</p><p class="small">Source issued ${time(evidence.time)}</p>${source?link(source.url,source.title):''}`;
}

function eventDetail(event) {
  return `<h3>M${number(event.magnitude)} / ${esc(event.place)}</h3><p>Recorded occurrence: ${time(event.time)}</p><dl><div><dt>Depth estimate</dt><dd>${number(event.depthKm)} km</dd></div><div><dt>Coordinates</dt><dd>${number(event.latitude)}°, ${number(event.longitude)}°</dd></div></dl>${link(event.url,'Open the agency event record')}`;
}

function sourceComparison(data) {
  const earlier=data.evidence.find(item=>item.id==='origin-earlier'),later=data.evidence.find(item=>item.id==='origin-current');
  if(!earlier||!later)return '';
  const precision=value=>typeof value==='number'?String(value):'Not supplied';
  return `<figure class="inside-comparison"><figcaption>Two retained origin solutions</figcaption><table><thead><tr><th scope="col">Agency estimate</th><th scope="col">Earlier saved</th><th scope="col">Later saved</th></tr></thead><tbody><tr><th scope="row">Magnitude</th><td>${number(earlier.magnitude)}</td><td>${number(later.magnitude)}</td></tr><tr><th scope="row">Depth, km</th><td>${precision(earlier.depthKm)}</td><td>${precision(later.depthKm)}</td></tr><tr><th scope="row">Stations used for location</th><td>${precision(earlier.originStations)}</td><td>${precision(later.originStations)}</td></tr></tbody></table><p>Both origins carry a USGS reviewed status and a preliminary evaluation status. These are successive estimates of one earthquake.</p><div>${link(M.sourceById(data,earlier.sourceId)?.url,'Earlier origin')} / ${link(M.sourceById(data,later.sourceId)?.url,'Later origin')}</div></figure>`;
}

function content() {
  const data=dataset(), latest=data.evidence.at(-1),event=data.event;
  const sourceFor=id=>data.sources.find(source=>source.id===id);
  const shakingSource=sourceFor(data.shaking?.sourceId);
  const faq='https://www.usgs.gov/faqs/what-difference-between-earthquake-magnitude-and-earthquake-intensity-what-modified-mercalli';
  const catalogSource=data.sources.find(source=>/catalog|catalogue/i.test(source.id+' '+source.title));
  const archiveSource=sourceFor('event-record');
  const correction=`mailto:richard@noteworthynews.co?subject=${encodeURIComponent('Correction request: '+title)}&body=${encodeURIComponent('Visual story: https://noteworthynews.co'+route+'\n\nWhat needs correcting:\n\nSupporting source:')}`;
  const chapterCopy=[
    {id:'overview',number:'01',label:'The earthquake',heading:'A location. An estimate.',text:`The saved USGS record lists this earthquake at magnitude ${number(event.magnitude)}, with an estimated depth of ${number(event.depthKm)} km. The marker shows the epicentre at the surface above the source.`,url:event.url,source:'USGS event record'},
    {id:'sequence',number:'02',label:'Regional context',heading:'Read the region in time.',text:`The saved, bounded catalogue contains ${data.events.length} recorded earthquakes. Move through their occurrence times. This selection does not establish that the events caused one another.`,url:catalogSource?.url,source:'Open the exact catalogue query'},
    {id:'shaking',number:'03',label:'Estimated shaking',heading:'Magnitude is only one measure.',text:'The shaded cells show local shaking estimates from the saved ShakeMap v4, issued September 12. These values are different from the earthquake’s magnitude. The edge of the supplied grid is not a boundary of its effects.',url:shakingSource?.url,source:'USGS shaking data'},
    {id:'evidence',number:'04',label:'The revisions',heading:'Watch the estimate evolve.',text:'Move through the preserved source versions using the slider below the map. The orange marker shows the location in a selected origin record, when supplied.',url:archiveSource?.url||event.url,source:'Preserved agency product history'}
  ];
  return `<article class="inside-report" data-inside-story>
  <header class="inside-heading"><div><div class="inside-series">Inside the Story <span>01 / Java Sea</span></div><h1>Deep beneath<br><em>the Java Sea.</em></h1></div><div><p class="inside-deck">USGS revised its estimate from magnitude 6.6 to 6.5. Explore one deep earthquake through the records that changed our picture of it.</p><p class="inside-credit">A visual explanation by Noteworthy News<br>From USGS data and preserved agency products</p><span class="inside-event-stamp">Earthquake: ${esc(dateOnly(event.time))} UTC / A source archive</span></div></header>
  <noscript><p class="inside-no-js">The complete account, map, source history and catalogue are available below. Interactive selection requires JavaScript.</p></noscript>
  <nav class="inside-chapters" aria-label="Explore the visual story" data-inside-controls hidden>${chapterCopy.map(chapter=>`<button type="button" data-inside-chapter="${chapter.id}" aria-pressed="${chapter.id==='overview'}"><span>${chapter.number}</span>${chapter.label}</button>`).join('')}</nav>
  <div class="inside-explorer"><div class="inside-map-column"><div class="inside-map-top"><strong>JAVA SEA &amp; SURROUNDING REGION</strong><span>North ↑ / Geographic source data</span></div>${map(data)}<div class="inside-map-legend"><span data-inside-map-layer="epicentre"><span class="legend-star">✚</span>Latest saved epicentre</span><span data-inside-map-layer="sequence" hidden><span class="legend-dot"></span>Recorded regional event</span><span data-inside-map-layer="shaking" hidden>Shading: MMI 2.8–2.9 / Saved ShakeMap v4, Sep 12</span><span class="inside-origin-key" data-inside-evidence-marker-legend hidden>○ Selected origin version</span></div><div class="inside-layers" data-inside-controls hidden aria-label="Map layers"><button type="button" data-inside-layer="epicentre" aria-pressed="true">Epicentre</button><button type="button" data-inside-layer="sequence" aria-pressed="false">Regional events</button><button type="button" data-inside-layer="shaking" aria-pressed="false">Shaking estimate</button></div></div>
  <aside class="inside-side-panel" aria-label="Reading the map">${chapterCopy.map(chapter=>`<div class="inside-caption" data-inside-chapter-copy="${chapter.id}" ${chapter.id==='overview'?'':'hidden'}><div class="eyebrow">${chapter.number} / ${chapter.label}</div><h2>${chapter.heading}</h2><p>${chapter.text}</p>${chapter.id==='evidence'?'<dl class="inside-version-stats"><div><dt>Magnitude in this version</dt><dd data-inside-evidence-stat="magnitude"></dd></div><div><dt>Depth in this version</dt><dd data-inside-evidence-stat="depthKm"></dd></div></dl><p data-inside-evidence-time-label class="small"></p>':''}${link(chapter.url,chapter.source)}</div>`).join('')}<hr class="inside-side-divider"><div class="inside-detail" data-inside-event-detail>${eventDetail(event)}</div></aside></div>
  <section class="inside-time-panel" data-inside-time-controls data-inside-controls hidden aria-label="Recorded earthquake timeline"><div class="inside-time-top"><label for="inside-time">Explore recorded event times</label><output id="inside-time-label" data-inside-time-label for="inside-time">${esc(M.formatTime(event.time))}</output></div><input id="inside-time" type="range" min="0" max="${data.timeline.length-1}" step="1" value="${data.timeline.length-1}" data-inside-time aria-describedby="inside-time-note"><div class="inside-time-footer"><p id="inside-time-note">This control replays occurrence times from the saved catalogue. It does not reconstruct what was known or published at each moment.</p><div class="inside-step-controls"><button type="button" data-inside-step="previous" aria-label="Previous recorded earthquake">←</button><button type="button" data-inside-step="next" aria-label="Next recorded earthquake">→</button></div></div></section>
  <div class="inside-source-control" data-inside-controls hidden data-inside-evidence-control data-inside-evidence-controls><label for="inside-evidence-version">Choose a preserved source version</label><select id="inside-evidence-version" data-inside-evidence>${data.evidence.map(item=>`<option value="${esc(item.id)}" ${item.id===latest?.id?'selected':''}>${esc(item.label)} / ${esc(M.formatTime(item.time))}</option>`).join('')}</select><label for="inside-evidence-time" class="inside-version-range-label">Move through the preserved source versions</label><input id="inside-evidence-time" type="range" min="0" max="${Math.max(0,data.evidence.length-1)}" step="1" value="${Math.max(0,data.evidence.length-1)}" data-inside-evidence-time><div class="inside-source-control-ends"><span>Earlier saved assessment</span><span>Later saved assessment</span></div><p class="small">Dates are agency product issue times. The earliest retained version is not necessarily the first public alert.</p></div>
  <div class="inside-state-bar"><p data-inside-status role="status" aria-live="polite">Latest saved agency account. No automatic playback.</p><button type="button" data-inside-reset data-inside-controls hidden>Reset view</button></div>
  <details class="inside-selection-list"><summary>Read the recorded events as a list (${data.events.length})</summary><p class="small">A bounded regional selection, not a complete list of every earthquake or a classification of aftershocks.</p><ol class="inside-event-list">${data.events.map(item=>`<li><button type="button" data-inside-event="${esc(item.id)}" aria-pressed="${item.id===event.id}" data-inside-controls hidden><strong>M${number(item.magnitude)}</strong> ${esc(M.formatTime(item.time))}<br>${esc(item.place)}</button><span data-inside-static-event>${link(item.url,`M${number(item.magnitude)} / ${M.formatTime(item.time)} / ${item.place}`)}</span></li>`).join('')}</ol></details>
  <div class="inside-story-body"><div class="inside-prose"><section id="inside-account"><div class="eyebrow">01 / The event</div><h2>One event, revised estimates.</h2><p>The USGS record places this earthquake in the Java Sea at ${esc(M.formatTime(event.time))}. Its later saved solution reports magnitude ${number(event.magnitude)} and a depth of ${number(event.depthKm)} kilometres.</p><p>An earlier preserved origin solution reports magnitude 6.6. The later 6.5 estimate belongs to the same event. A revised estimate changes the scientific account; it does not mean the earthquake itself happened again.</p>${link(archiveSource?.url||event.url,'Inspect the agency’s event and product history')}${sourceComparison(data)}<p class="inside-pullquote">The number in a headline is a measurement. Its source history is part of the story.</p></section>
  <section id="inside-intensity"><div class="eyebrow">02 / Reading the shaking</div><h2>One magnitude, different intensities.</h2><p>Magnitude describes the size of an earthquake at its source. Intensity describes shaking at a location, so it can differ from place to place. The map’s MMI values describe the agency’s estimated shaking, not a second magnitude.</p>${link(faq,'USGS: magnitude and intensity')}<p>This feature uses the supplied ShakeMap grid. The displayed low-resolution grid spans MMI 2.8–2.9. This is the range in this supplied grid, not a claim about the maximum shaking everywhere. Its cells are estimates, not individual sensor readings or reports of damage. Areas outside that grid are outside the display’s coverage; they are not evidence of no shaking.</p>${link(shakingSource?.url,'Inspect the supplied ShakeMap product')}</section>
  <section id="inside-region"><div class="eyebrow">03 / The regional record</div><h2>Context without a causal claim.</h2><p>The regional view uses a fixed geographic area, date window and minimum magnitude. Moving the slider reveals records in their occurrence order. It does not assign them to an aftershock sequence or show when the records first became available.</p><p>Catalogues are revised. The values here come from the saved retrieval described in the methodology, even when you move back to an earlier event time.</p>${link(catalogSource?.url,'Inspect the exact catalogue selection')}</section></div>
  <aside class="inside-reading-aside"><h2>What this can tell us</h2><ul><li>Where USGS locates the earthquake and how its retained origin estimates differ.</li><li>What the supplied agency model estimates about local shaking.</li><li>Which catalogue events meet this feature’s stated regional selection.</li></ul><h2>What it cannot establish</h2><ul><li>Damage, casualties or conditions at an individual address.</li><li>Whether nearby earthquakes caused one another.</li><li>The full history of every alert or everything known at the time.</li></ul><p>Use the original agency record for current information. This is a visual explanation of saved source material.</p>${link(event.url,'USGS event page')}<dl><dt>Source retrieval</dt><dd>${time(data.fetchedAt||data.retrievedAt||data.sources[0]?.retrievedAt)}</dd><dt>Editorial responsibility</dt><dd>Noteworthy News. Individual editor review is pending for this development feature.</dd><dt>Underlying publication</dt><dd><a href="/article.html?id=usgs-us7000tgrk">Read the original Noteworthy update →</a></dd></dl></aside></div>
  <section class="inside-evidence" id="inside-evidence"><div class="eyebrow">04 / The preserved source history</div><h2>What the source said then. What it says later.</h2><p>Move between the actual retained USGS products. These are dated agency versions, not a reconstruction of the newsroom’s knowledge. Each update keeps its original issue time.</p><div class="inside-evidence-detail" data-inside-evidence-detail>${evidenceCard(data,latest)}</div><ol class="inside-evidence-history">${data.evidence.map(item=>`<li>${time(item.time)}<h3>${esc(item.label)}</h3><p>${esc(item.text)}</p>${link(M.sourceById(data,item.sourceId)?.url,'Open this source version')}</li>`).join('')}</ol></section>
  <section class="inside-source-ledger" id="inside-methodology"><div class="eyebrow">Methodology &amp; source documents</div><h2>Follow the evidence all the way back.</h2><p>The map uses a local equirectangular projection with geographic coordinates. Shading comes from a sampled agency grid; marker size identifies events and is not an energy or damage scale. Geographic labels are contextual. This feature makes no casualty or forecasting calculation.</p><p>Catalogue selection: ${esc(data.catalogue.description)} Window: ${esc(M.formatTime(data.catalogue.startTime))} to ${esc(M.formatTime(data.catalogue.endTime))}. Minimum magnitude ${number(data.catalogue.minimumMagnitude)}; bounds ${data.bounds[0]}–${data.bounds[2]}°E and ${Math.abs(data.bounds[1])}–${Math.abs(data.bounds[3])}°S. Saved records are not automatically refreshed.</p><ol>${data.sources.map(source=>`<li id="inside-source-${esc(source.id)}"><span>${esc(source.kind||'Source document')}</span>${link(source.url,source.title)}${source.description?`<p>${esc(source.description)}</p>`:''}<p>${source.issuedAt?'Source issued '+time(source.issuedAt)+' / ':''}Retrieved ${time(source.retrievedAt)}</p></li>`).join('')}</ol><p><a class="inline-source" href="/publication/inside-story/data/java-sea-2026.json" download>Download the source dataset ↓</a> / <a class="inline-source" href="/publication/inside-story/data/provenance.json" download>Download provenance and source hashes ↓</a></p></section>
  <div class="inside-end"><div><h2>A correction belongs in the record.</h2><p>Share a source that changes this account. Substantive corrections will be identified separately from ordinary agency updates.</p><a href="${esc(correction)}">Send a correction with evidence →</a></div><a class="button" href="/story-so-far/">Explore more source briefings →</a></div>
  <script type="application/json" id="inside-story-data">${json(data)}</script></article>`;
}

module.exports={route,title,description,dataset,geometryPath,map,feature,articleContext,content};
