/**
 * Noteworthy News — email design tokens.
 *
 * Mapped from the live site's design system (v2/styles/tokens.css + v4.css),
 * flattened to email-safe solid hex values. Every template consumes these —
 * never raw values — so the whole system can be retuned in one place.
 *
 * Email constraints honored here:
 *  - solid hex only (rgba backgrounds are unreliable in Outlook)
 *  - system font stacks (site webfonts Sora/Source Serif 4 fall back to
 *    their closest email-safe equivalents)
 *  - all contrast pairs checked against WCAG AA on their intended surfaces
 */

const color = {
  // Surfaces (site: --color-bg #04060B, panels #090E17/#0C1220, raised #101827)
  bg: '#04060B',          // outer canvas
  card: '#0A101C',        // main 600px card
  panel: '#0D1526',       // inset panels / modules
  raised: '#111A2E',      // hero panels, code-like blocks

  // Hairlines (solid equivalents of the site's white-alpha borders)
  border: '#1E2839',      // ~ rgba(255,255,255,0.08) on card
  borderSoft: '#161F2E',  // ~ rgba(255,255,255,0.055)
  borderLit: '#2A3A55',   // hover/emphasis border

  // Type (site: rgba(240,242,245, .95/.55/.32))
  text: '#F0F2F5',
  textSecondary: '#98A2B3',
  textMuted: '#5F6B7E',   // de-emphasis only, never for load-bearing copy

  // Accent — action blue (site: #3B8BF2). Body links use the brighter
  // hover tone for contrast on dark.
  accent: '#3B8BF2',
  accentBright: '#5BA0F5',

  // Live / severity system (mirrors the site's alert chips)
  live: '#EF4444',
  critical: '#F87171',    // text-safe red on dark panels
  elevated: '#F59E0B',
  monitor: '#5BA0F5',
  stable: '#34D399',

  // Gold — editorial authority, used only for the brief's issue marker
  gold: '#D9B545',

  // On-accent
  white: '#FFFFFF',
};

const font = {
  // Site headings are Sora (geometric sans); UI is Inter.
  ui: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  // Site body is Source Serif 4 — Georgia is its email-safe stand-in.
  serif: "Georgia, 'Times New Roman', Times, serif",
  // Timestamps, issue numbers, source labels.
  mono: "'SF Mono', 'Courier New', Courier, monospace",
};

/** Severity → chip colors. Matches v2 tokens (critical/elevated/monitor/stable). */
const severity = {
  critical: { text: '#F87171', border: '#7F2D2D', label: 'CRITICAL' },
  elevated: { text: '#F59E0B', border: '#7C5A10', label: 'ELEVATED' },
  monitor:  { text: '#5BA0F5', border: '#274B7E', label: 'MONITOR' },
  stable:   { text: '#34D399', border: '#1D5C43', label: 'STABLE' },
};

/** Story status → chip colors. The site's live-story language. */
const status = {
  developing: { text: '#F59E0B', border: '#7C5A10', label: 'DEVELOPING' },
  confirmed:  { text: '#34D399', border: '#1D5C43', label: 'CONFIRMED' },
  corrected:  { text: '#F87171', border: '#7F2D2D', label: 'CORRECTED' },
  watch:      { text: '#5BA0F5', border: '#274B7E', label: 'WATCH' },
  resolved:   { text: '#98A2B3', border: '#2A3A55', label: 'RESOLVED' },
};

const urls = {
  site: 'https://noteworthynews.co',
  topStories: 'https://noteworthynews.co/#feed',
  liveStories: 'https://noteworthynews.co/#live',
  howWeVerify: 'https://noteworthynews.co/how-we-verify.html',
  editorialPolicy: 'https://noteworthynews.co/editorial-policy.html',
  logo: 'https://noteworthynews.co/IMG_5794.PNG',
  // Generated by scripts/generate-noteworthy-email-gif.js, hosted by the
  // site itself (publish dir is repo root, so /email-assets/* is public).
  liveSignalGif: 'https://noteworthynews.co/email-assets/noteworthy-live-signal.gif',
};

module.exports = { color, font, severity, status, urls };
